# implentation of any 50 numpy methods or attribute codes in jupyter notebook

In [1]:
import numpy as np

In [3]:
#1. print the version number
print(np.__version__)

1.16.5


In [16]:
#2. Create a 1D array of numbers from 0 to 9
arr=np.arange((10),dtype=complex)
print(arr)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [9]:
#3.How to create a boolean array?
arr=np.full((3,3),True,dtype=bool)
print(arr)
# Alternate method:
arr=np.ones((3,3), dtype=bool)
print("Alternate method\n",arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Alternate method
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
#4. Shape of array in question 3
arr=np.full((3,3),True,dtype=bool)
print(arr)
print(arr.shape)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
(3, 3)


In [13]:
#5. the type of the elements in the array in question 3
arr=np.full((3,3),True)
print(arr)
print(arr.dtype)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
bool


In [22]:
#6. How to compute the mean
a = np.arange(12).reshape(3,4)
print(a)
print("mean=",np.mean(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean= 5.5


In [21]:
#7. How to compute the median
a = np.arange(12).reshape(3,4)
print(a)
print("median=",np.median(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
median= 5.5


In [23]:
#8. How to compute the average
a = np.arange(12).reshape(3,4)
print(a)
print("average=",np.average(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
average= 5.5


In [24]:
#9. How to compute the cumprod
a = np.arange(12).reshape(3,4)
print(a)
print("cumprod=",np.cumprod(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
cumprod= [0 0 0 0 0 0 0 0 0 0 0 0]


In [25]:
#10. How to compute the prod
a = np.arange(12).reshape(3,4)
print(a)
print("prod=",np.prod(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
prod= 0


In [33]:
#11. Get the positions of top 5 maximum values in a given array a.
a = np.random.uniform(1,50, 20)
print(a)
print(a[a.argsort()][-5:])

[19.43637026 30.04746465 31.8671519   7.98741541 46.75822367 47.37261416
 30.51253623 20.00054774 18.7962122  11.01291857 14.56148801 13.08025818
  9.50679209 48.36387503 47.89361742 30.30071053 36.8337369  17.67887592
  5.51072457 23.71140293]
[36.8337369  46.75822367 47.37261416 47.89361742 48.36387503]


In [35]:
#12. sort the array
a = np.random.uniform(1,50, 20)
print(a)
print(a[a.sort()])

[39.13617156 39.20032153 30.90607951 16.14101708 35.18901047 43.12129649
 31.64086413 49.13798365 48.84850622  9.16801243  2.13572869  8.87648288
 46.25134444 47.72394264 11.33794252 18.66573729 27.91938782 14.31971161
 23.56947943 35.11191668]
[[ 2.13572869  8.87648288  9.16801243 11.33794252 14.31971161 16.14101708
  18.66573729 23.56947943 27.91938782 30.90607951 31.64086413 35.11191668
  35.18901047 39.13617156 39.20032153 43.12129649 46.25134444 47.72394264
  48.84850622 49.13798365]]


In [38]:
#13. argmax
a = np.random.uniform(1,50, 20)
print(a)
print(a[np.argmax(a)])

[11.20215477 23.11167258 25.1003026  45.05473942 36.73866259 38.73439887
 19.39652313 17.84323723 33.09672509 35.84086167  6.56334119  7.51840578
 23.34591382  8.82707528 48.12045328 42.0431715  26.48787366 11.69534063
  7.6110174  48.97444693]
48.974446928709575


In [39]:
#14. argmin
a = np.random.uniform(1,50, 20)
print(a)
print(a[np.argmin(a)])

[35.64513129 43.13880229 19.97145876 13.29086697 15.67246293 42.98788089
 24.17621554 33.5005753  40.48070176 13.39604473  4.89909851 36.90526965
 48.1084764  47.73643197 25.03445354 31.97741116 36.91675597 45.21806566
  8.95009902 20.8881848 ]
4.899098509545919


In [50]:
#15. cross
a = np.random.randint(20, size=[2,3])
b = np.random.randint(20, size=[2,3])
print(a)
print(b)
print(np.cross(a,b, axisc=0))

[[13  1  4]
 [19  1  0]]
[[ 6  3  3]
 [19 18  9]]
[[  -9    9]
 [ -15 -171]
 [  33  323]]


In [57]:
#16. maximum for each row in the given array.
a = np.random.randint(1,10, [5,3])
print(a)
print(np.max(a, axis=1))

[[9 2 6]
 [2 8 2]
 [3 7 6]
 [8 5 8]
 [3 4 7]]
[9 8 7 8 7]


In [58]:
#16. maximum in the given array.
a = np.random.randint(1,10, [5,3])
print(a)
print(np.max(a))

[[3 3 5]
 [4 6 2]
 [6 2 4]
 [8 4 6]
 [6 1 5]]
8


In [60]:
#17. maximum for each column in the given array.
a = np.random.randint(1,10, [5,3])
print(a)
print(np.max(a, axis=0))

[[2 9 8]
 [6 5 1]
 [8 3 5]
 [9 3 1]
 [3 6 8]]
[9 9 8]


In [61]:
#18.Drop all nan values from a 1D numpy array
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)
print(a[~np.isnan(a)])


[ 1.  2.  3. nan  5.  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


In [62]:
#19.#18.Drop all non-nan values from a 1D numpy array
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)
print(a[np.isnan(a)])

[ 1.  2.  3. nan  5.  6.  7. nan]
[nan nan]


In [64]:
#20. euclidean distance between two arrays a and b
a = np.array([1,2,3,4,5])
print(a)
b = np.array([4,5,6,7,8])
print(b)
dist = np.linalg.norm(a-b)
print(dist)

[1 2 3 4 5]
[4 5 6 7 8]
6.708203932499369


In [67]:
#21.  Subtract the 1d array b from the 2d array a, such that each item of b subtracts from respective row of a.
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a)
b = np.array([1,2,3])
print(b)
print("Ans:",a - b[:,None])

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
Ans: [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [68]:
#22.  Add the 1d array b from the 2d array a, such that each item of b adds from respective row of a.
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a)
b = np.array([1,2,3])
print(b)
print("Ans:",a + b[:,None])

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
Ans: [[4 4 4]
 [6 6 6]
 [8 8 8]]


In [69]:
#23. prod the 1d array b_1d from the 2d array a_2d, such that each item of b_1d prod from respective row of a_2d.
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a)
b = np.array([1,2,3])
print(b)
print("Ans:",a * b[:,None])

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
Ans: [[ 3  3  3]
 [ 8  8  8]
 [15 15 15]]


In [70]:
#24. divide the 1d array b_1d from the 2d array a_2d, such that each item of b_1d divide from respective row of a_2d.
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a)
b = np.array([1,2,3])
print(b)
print("Ans:",a / b[:,None])

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
Ans: [[3.         3.         3.        ]
 [2.         2.         2.        ]
 [1.66666667 1.66666667 1.66666667]]


In [71]:
#25. mod the 1d array b_1d from the 2d array a_2d, such that each item of b_1d mod from respective row of a_2d.
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
print(a)
b = np.array([1,2,3])
print(b)
print("Ans:",a % b[:,None])

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
Ans: [[0 0 0]
 [0 0 0]
 [2 2 2]]


In [78]:
#26. ix_() function
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
print(a)
print(b)
print(c)
ax,bx,cx = np.ix_(a,b,c)
result = ax+bx*cx
print("\nax+bx*cx=\n",result)

[2 3 4 5]
[8 5 4]
[5 4 6 8 3]

ax+bx*cx=
 [[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]


In [80]:
#27.  Extract all even numbers from arr
a=np.arange(25).reshape(5,5)
print(a)
b=a[a % 2 == 0]
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [91]:
#28.  Replace all odd numbers in arr with -1
a=np.arange(25).reshape(5,5)
print(a)
print(np.where(a % 2 == 1, -1, a))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]
 [10 -1 12 -1 14]
 [-1 16 -1 18 -1]
 [20 -1 22 -1 24]]


In [93]:
#28.  Replace all even numbers in arr with 1
a=np.arange(25).reshape(5,5)
print(a)
print(np.where(a % 2 == 0, 1, a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  1  1  3  1]
 [ 5  1  7  1  9]
 [ 1 11  1 13  1]
 [15  1 17  1 19]
 [ 1 21  1 23  1]]


In [96]:
#29. ndarray.itemsize (itemsize 4 (=32/8)
a=np.arange(25).reshape(5,5)
print(a)
print(a.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
4


In [98]:
#30. a.dtype.name
a=np.arange(25).reshape(5,5)
print(a)
print(a.dtype.name)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
int32


In [99]:
#31 a.ndim, the number of axes (dimensions) of the array
a=np.arange(25).reshape(5,5)
print(a)
print(a.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2


In [100]:
#32. zeros
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [101]:
#33. ones
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [102]:
#34 np.arange it accepts float arguments
a=np.arange( 0, 2, 0.3 ) 
print(a)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [104]:
#35 linspace  # useful to evaluate function at lots of points
from numpy import pi
a=np.linspace( 0, 2*pi, 100 ) 
print(a)


[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [106]:
#36 dot function
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)
print("dot:",A.dot(B))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
dot: [[5 4]
 [3 4]]


In [109]:
#37 * operates  elementwise product
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)
print("*elementwise product:",A*B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
*elementwise product: [[2 0]
 [0 4]]


In [111]:
#38 matrix product
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)
print("matrix product:",A@B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
matrix product: [[5 4]
 [3 4]]


In [115]:
#39 a.sum()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.sum(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
3.10571095


In [119]:
#40 a.max()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.max(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
0.82770259


In [120]:
#41 a.min()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.min(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
0.02755911


In [121]:
#42 a.round()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.round(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
[[1. 0. 1.]
 [0. 1. 1.]]


In [123]:
#43 a.sqrt()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.sqrt(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
[[0.90978162 0.63968675 0.74134586]
 [0.16600937 0.86805133 0.73358252]]


In [124]:
#44 a.trace()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.trace(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
1.5812157


In [125]:
#45 a.transpose()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.transpose(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
[[0.82770259 0.02755911]
 [0.40919914 0.75351311]
 [0.54959369 0.53814331]]


In [126]:
#46 a.corrcoef()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.corrcoef(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
[[ 1.         -0.99908168]
 [-0.99908168  1.        ]]


In [127]:
#47 a.floor()
a = ([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])
print(a)
print(np.floor(a))

[[0.82770259, 0.40919914, 0.54959369], [0.02755911, 0.75351311, 0.53814331]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [129]:
#48 slicing
a = np.arange(10)**3
print(a)
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]


In [131]:
#49 np.ravel(a)
a = np.arange(10)**3
print(a)
print(np.ravel(a)) # returns the array, flattened

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]


In [143]:
#50 Deep Copy¶
a= ([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])
print(a)
c=a.copy()
print(c)

[[6.0, 7.0, 6.0, 9.0, 0.0, 5.0, 4.0, 0.0, 6.0, 8.0, 5.0, 2.0], [8.0, 5.0, 5.0, 7.0, 1.0, 8.0, 6.0, 7.0, 1.0, 8.0, 1.0, 0.0]]
[[6.0, 7.0, 6.0, 9.0, 0.0, 5.0, 4.0, 0.0, 6.0, 8.0, 5.0, 2.0], [8.0, 5.0, 5.0, 7.0, 1.0, 8.0, 6.0, 7.0, 1.0, 8.0, 1.0, 0.0]]


# END