# Assignment For Numpy¶
#Difficulty Level Beginner

In [1]:
#1. Import the numpy package under the name np
import numpy as np

In [2]:
#2. Create a null vector of size 10
a= np.zeros(10)
print ("null vector of size 10 is a =", a)
print("_________________________________________________")

null vector of size 10 is a = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
_________________________________________________


In [3]:
#3. Create a vector with values ranging from 10 to 49
values_ranging = np.arange(10,50)
print ("vector with values ranging from 10 to 49 are:", values_ranging)
print("_________________________________________________")

vector with values ranging from 10 to 49 are: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
_________________________________________________


In [4]:
#Find the shape of previous array in question 3
print("shape of previous array in question 3 is:",values_ranging.shape)
print("_________________________________________________")

shape of previous array in question 3 is: (40,)
_________________________________________________


In [5]:
#Print the type of the previous array in question 3
print("type of the previous array in question 3 is:", values_ranging.dtype)
print("_________________________________________________")

type of the previous array in question 3 is: int32
_________________________________________________


In [6]:
#Print the numpy version and the configuration
print("Numpy Version")
print(np.__version__)
print("_________________________________________________")
print("Configuration")
print(np.show_config())
print("_________________________________________________")

Numpy Version
1.16.5
_________________________________________________
Configuration
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Fil

In [7]:
#Print the dimension of the array in question 3
print("the dimension of the array in question 3 is:",values_ranging.ndim)
print("_________________________________________________")

the dimension of the array in question 3 is: 1
_________________________________________________


In [8]:
#Create a boolean array with all the True values
# Array for random sampling
sample_arr = [True]
# Create a numpy array with random True or False of size 10
bool_arr = np.random.choice(sample_arr, size=10)
print('Numpy Array: ')
print(bool_arr)
print("_________________________________________________")

Numpy Array: 
[ True  True  True  True  True  True  True  True  True  True]
_________________________________________________


In [9]:
#Create a two dimensional array
Two_array = np.zeros((4,5))
# 4 rows, 5 columns
print("2-d array:", Two_array)
print("_________________________________________________")

2-d array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
_________________________________________________


In [10]:
#Create a three dimensional array
Three_array = np.zeros((3,3,4))
#3 Sets, 3 Rows per Set, 4 Columns
print("3-d array:", Three_array)
print("_________________________________________________")
print("**************************************************")

3-d array: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
_________________________________________________
**************************************************


# Difficulty Level Easy

In [11]:
# 1.Reverse a vector (first element becomes last)
x = np.arange(1, 20)
print("Original array:", x)
x = x[::-1]
print("Reverse array:", x)
print("_________________________________________________")

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
_________________________________________________


In [12]:
# 2.Create a null vector of size 10 but the fifth value which is 1
a=np.zeros(10)
print("original null vector:",a)
a[5]=1
print("5th value changed in a null vector:",a)
print("_________________________________________________")

original null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5th value changed in a null vector: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
_________________________________________________


In [13]:
# 3.Create a 3x3 identity matrix
array_2D=np.identity(3)
print('3x3 matrix:', array_2D)
print("_________________________________________________")

3x3 matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
_________________________________________________


In [14]:
# arr = np.array([1, 2, 3, 4, 5])
#Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
print("original array:",arr)
print("original array data type:",arr.dtype) 
# change the dtype to 'float64' 
arr = arr.astype('float64') 
# Print the array after changing 
# the data type 
print("converted array:",arr)
# Also print the data type 
print("converted array data type:", arr.dtype) 
print("_________________________________________________")

original array: [1 2 3 4 5]
original array data type: int32
converted array: [1. 2. 3. 4. 5.]
converted array data type: float64
_________________________________________________


In [15]:
#arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
#arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
print("arr1 =",arr1)  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("arr2 =",arr2) 
out_arr = np.multiply(arr1, arr2)  
print ("Resultant output array: ", out_arr)  
print("_________________________________________________")

arr1 = [[1. 2. 3.]
 [4. 5. 6.]]
arr2 = [[ 0.  4.  1.]
 [ 7.  2. 12.]]
Resultant output array:  [[ 0.  8.  3.]
 [28. 10. 72.]]
_________________________________________________


In [16]:
#arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
#arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
#Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
print("arr1 =",arr1)  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("arr2 =",arr2) 
comparison = arr1 == arr2 
equal_arrays = comparison.all() 
print("comparison result is:", equal_arrays) 
print("_________________________________________________")

arr1 = [[1. 2. 3.]
 [4. 5. 6.]]
arr2 = [[ 0.  4.  1.]
 [ 7.  2. 12.]]
comparison result is: False
_________________________________________________


In [17]:
#Extract all odd numbers from arr with values(0-9)
a = np.array([1,2,3,4,5,6,6,7,8,9])
odd=a[a % 2 == 1]
print("odd number from array are:",odd)
print("_________________________________________________")

odd number from array are: [1 3 5 7 9]
_________________________________________________


In [18]:
#Replace all odd numbers to -1 from previous array
a = np.array([1,2,3,4,5,6,6,7,8,9])
odd = (a%2 == 1)
a[odd] = -1
print("odd number replaced with -1 array are:",a)
print("_________________________________________________")


odd number replaced with -1 array are: [-1  2 -1  4 -1  6  6 -1  8 -1]
_________________________________________________


In [19]:
#arr = np.arange(10)
#Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
print("original array",arr)
arr[5:8]=12
print("Changed array",arr)
print("_________________________________________________")

original array [0 1 2 3 4 5 6 7 8 9]
Changed array [ 0  1  2  3  4 12 12 12  8  9]
_________________________________________________


In [20]:
#Create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array:")
x[1:-1,1:-1] = 0
print(x)
print("_________________________________________________")

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
_________________________________________________


# Difficulty Level Medium

In [21]:
#arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array:", arr2d)
arr2d[1][1]=12
print("modified array:",arr2d)
print("_________________________________________________")

original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
modified array: [[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
_________________________________________________


In [22]:
#arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("original array:", arr3d)
arr3d[0] = 64
print("modified array:",arr3d)
print("_________________________________________________")

original array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
modified array: [[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]
_________________________________________________


In [27]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr = np.arange(9),
arr= np.reshape(arr,(3,3))
print("original array:", arr)
print("sliced 1st 1-D array:", arr[0, 0:])
print("_________________________________________________")

original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
sliced 1st 1-D array: [0 1 2]
_________________________________________________


In [26]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
arr = np.arange(9),
arr= np.reshape(arr,(3,3))
print("original array:", arr)
print("sliced 2nd value from 2nd 1-D array:", arr[1, 1:2])
print("_________________________________________________")

original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
sliced 2nd value from 2nd 1-D array: [4]
_________________________________________________


In [28]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
arr = np.arange(9),
arr= np.reshape(arr,(3,3))
print("original array:", arr)
print("sliced the third column but only the first two rows of array:", arr[0:2,2])
print("_________________________________________________")

original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
sliced the third column but only the first two rows of array: [2 5]
_________________________________________________


In [29]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
print("_________________________________________________")

Original Array:
[[0.80303652 0.61874006 0.23233397 0.78606801 0.41294445 0.14668654
  0.14658285 0.01204494 0.42845876 0.38055879]
 [0.32793669 0.05114814 0.09973965 0.20668394 0.78037917 0.92363441
  0.85731669 0.78455885 0.25209278 0.25481   ]
 [0.96039083 0.00661416 0.51759936 0.24882819 0.18996996 0.86891619
  0.74076336 0.93323581 0.61888511 0.40522951]
 [0.98023485 0.87102087 0.25222661 0.43084484 0.14690802 0.54245811
  0.76665745 0.0649879  0.20046235 0.83746013]
 [0.48522565 0.93473481 0.55813724 0.25684105 0.40301238 0.6199471
  0.40977306 0.69710057 0.34275251 0.07100583]
 [0.28523787 0.31565629 0.6605142  0.65779027 0.77268714 0.62480961
  0.60134739 0.10498358 0.46218495 0.98733059]
 [0.29301704 0.81693475 0.71997039 0.08406167 0.27913574 0.67273819
  0.45317294 0.51602506 0.61662854 0.26909354]
 [0.34381873 0.86835279 0.6421335  0.04935159 0.50239289 0.98813725
  0.58578345 0.26582069 0.41439719 0.71006979]
 [0.17882608 0.89260298 0.10052465 0.50583349 0.39177728 0.697446

In [30]:
#Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
print("a:",a) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("b:",b)
# Common values between two arrays 
print("Common values between a and b:",np.intersect1d(a, b)) 
print("_________________________________________________")

a: [1 2 3 2 3 4 3 4 5 6]
b: [ 7  2 10  2  7  4  9  4  9  8]
Common values between a and b: [2 4]
_________________________________________________


In [31]:
#Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
print("a:",a) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("b:",b)
print("the positions where elements of a and b match in array a:",np.searchsorted(a, np.intersect1d(a, b)))
print("_________________________________________________")

a: [1 2 3 2 3 4 3 4 5 6]
b: [ 7  2 10  2  7  4  9  4  9  8]
the positions where elements of a and b match in array a: [1 5]
_________________________________________________


In [32]:
#Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("names:", names) 
data = np.random.randn(7, 4)
print("data:", data)
x = np.where(names != 'Will')
print(x)
n=names != 'Will'
print(n)
print("_________________________________________________")

names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data: [[ 0.87231019 -1.15971271 -0.52384585 -0.65224362]
 [ 1.107436   -1.21890519 -0.33274988 -1.18193006]
 [ 2.15912599  1.2447166   0.38102217  1.21193069]
 [ 1.46582817  0.6470612   0.1073656  -0.81858823]
 [ 0.58094412 -1.12858479 -0.11955043  0.00568945]
 [ 1.74721731  0.71598092  1.11458398  0.28396193]
 [ 0.38079215 -1.27349545  0.08230434 -0.58502849]]
(array([0, 1, 3, 5, 6], dtype=int64),)
[ True  True False  True False  True  True]
_________________________________________________


In [33]:
#Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("names:", names) 
data = np.random.randn(7, 4)
print("data:", data)
mask = (names == 'Bob')
# mask = (names != 'Will') | (names != 'Joe')
print(mask)
print("_________________________________________________")

names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data: [[-2.25166073  0.73508792  0.35924518 -1.28388453]
 [ 0.11797662 -1.996798   -0.03619846 -0.48226592]
 [-1.03556693 -1.23319681 -0.78576936  0.90249997]
 [ 0.0112956   0.16606049 -0.25184631 -1.38561558]
 [ 0.78287728  0.3631321   0.07254136 -0.57860244]
 [ 0.43288348  0.34113867  0.3715422   0.25034713]
 [-0.47359856  0.11123742  0.12395083 -0.99207797]]
[ True False False  True False False False]
_________________________________________________


# Difficulty Level Hard

In [34]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15
arr = np.arange(1,16).reshape(5,3)
print(arr)
print("_________________________________________________")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
_________________________________________________


In [35]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
arr = np.arange(16).reshape(2,2,4)
print(arr)
print("_________________________________________________")

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
_________________________________________________


In [37]:
#Swap axes of the array you created in Question 32
arr = np.arange(16).reshape(2,2,4)
print("array:",arr)
print("axes swaped of array:",arr.swapaxes(1, 2))
print("_________________________________________________")

array: [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
axes swaped of array: [[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
_________________________________________________


In [38]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
arr = np.arange(10)
print("arr:",arr)
x=np.sqrt(arr)
print("square root of every element in the array:", x)
print("Replace all elements of the said array with 0 which are less than 0.5")
x[x < 0.5] = 0
print(x)
print("_________________________________________________")

arr: [0 1 2 3 4 5 6 7 8 9]
square root of every element in the array: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Replace all elements of the said array with 0 which are less than 0.5
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
_________________________________________________


In [39]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
a=np.random.randint(1,12,6)
print(a)
b=np.random.randint(1,12,6)
print(b)
m=np.maximum(a,b)
print("maximum values between each element of the two arrays:",m)
print("_________________________________________________")

[11 11  7 10  5 10]
[8 7 6 5 8 4]
maximum values between each element of the two arrays: [11 11  7 10  8 10]
_________________________________________________


In [40]:
#Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
n=np.unique(names)
print(n)
print("_________________________________________________")

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']
_________________________________________________


In [41]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5]) 
print(a)
b = np.array([5,6,7,8,9])
print(b)
result = np.setdiff1d(a, b)
print(result)
print("_________________________________________________")

[1 2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]
_________________________________________________


In [42]:
#Following is the input NumPy array delete column two and insert following new column in its place
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("original array:",sampleArray)
print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)
newColumn = np.array([[10,10,10]])
print("new Column:",newColumn)
print("Array after inserting column 2")
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)
print("_________________________________________________")

original array: [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
new Column: [[10 10 10]]
Array after inserting column 2
[[34 10 73]
 [82 10 12]
 [53 10 66]]
_________________________________________________


In [43]:
#Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print("x=",x)
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("y=",y)
d=np.dot(a, b)
print("dot product of x and y=",d)
print("_________________________________________________")

x= [[1. 2. 3.]
 [4. 5. 6.]]
y= [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
dot product of x and y= 115
_________________________________________________


In [44]:
#Generate a matrix of 20 random values and find its cumulative sum
A = np.random.randint(20, size=(4,5))
print("matrix A:",A)
CS = np.cumsum(A)
print("cumulative sum of matrix A:",CS)
print("_________________________________________________")

matrix A: [[ 7 12 14  3  6]
 [ 4 13  3 19  9]
 [ 2  8  6 15 16]
 [ 7 18 17 12 14]]
cumulative sum of matrix A: [  7  19  33  36  42  46  59  62  81  90  92 100 106 121 137 144 162 179
 191 205]
_________________________________________________


# END