# Numpy_Assignment_2::

In [1]:
import numpy as np

In [3]:
#Question:1
#Convert a 1D array to a 2D array with 2 rows?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print("2-d array",arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2-d array [[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
#Question:2
#How to stack two arrays vertically?
x=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print(x)
y=np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
print(y)
array=np.vstack((x,y))
print("array:",array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
array: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
#Question:3
#How to stack two arrays horizontally?
x=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print(x)
y=np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
print(y)
array=np.hstack((x,y))
print("array:",array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
array: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [6]:
#Question:4
#How to convert an array of arrays into a flat 1d array?
arr = np.array([[0,1, 2], [3,4, 5],[6,7,8],[9,10,11], [12,13,14]])
print("arr=",arr)
newarr = arr.reshape(-1)
print("newarr=", newarr)

arr= [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
newarr= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
#Question:5
#How to Convert higher dimension into one dimension?
arr = np.arange(15).reshape(3,5)
print(arr)
newarr = arr.reshape(-1)
print("newarr=", newarr)
print("_________________________________________________")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
newarr= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
_________________________________________________


In [12]:
#Question:6
#Convert one dimension to higher dimension?
arr = np.arange(15)
print(arr)
newarr = arr.reshape(5, 3)
print("newarr=", newarr)
print("_________________________________________________")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
newarr= [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
_________________________________________________


In [13]:
#Question:7
#Create 5x5 an array and find the square of an array?
x = np.arange(25).reshape(5,5)
print(x)
s=np.square(x)
print("square of an array:",s)
print("_________________________________________________")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
square of an array: [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
_________________________________________________


In [14]:
#Question:8
#Create 5x6 an array and find the mean?
x = np.arange(30).reshape(5,6)
print(x)
m=np.mean(x)
print("mean of an array:",m)
print("_________________________________________________")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mean of an array: 14.5
_________________________________________________


In [15]:
#Question:9
#Find the standard deviation of the previous array in Q8?
x = np.arange(30).reshape(5,6)
print(x)
std=np.std(x, dtype=np.float64)
print("standard deviation of an array:",std)
print("_________________________________________________")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
standard deviation of an array: 8.65544144839919
_________________________________________________


In [16]:
#Question:10
#Find the median of the previous array in Q8?
x = np.arange(30).reshape(5,6)
print(x)
median=np.median(x)
print("median of an array:",median)
print("_________________________________________________")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
median of an array: 14.5
_________________________________________________


In [17]:
#Question:11¶
#Find the transpose of the previous array in Q8?
x = np.arange(30).reshape(5,6)
print(x)
t=x.transpose()
print("transpose of an array:",t)
print("_________________________________________________")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
transpose of an array: [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
_________________________________________________


In [18]:
#Question:12
#Create a 4x4 an array and find the sum of diagonal elements?
x = np.arange(16).reshape(4,4)
print(x)
# calculating the Trace of a matrix 
trace = np.trace(x) 
print("\nTrace of given matrix:",trace)
print("_________________________________________________")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace of given matrix: 30
_________________________________________________


In [19]:
#Question:13
#Find the determinant of the previous array in Q12?
x = np.arange(16).reshape(4,4)
print(x)
print ("determinant of the array:",np.linalg.det(x))
print("_________________________________________________")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
determinant of the array: -2.9582283945787796e-30
_________________________________________________


In [20]:
#Question:14
#Find the 5th and 95th percentile of an array?
# 2D array 
arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4,]] 
print("arr:", arr) 
#axis = 0 means along the column and axis = 1 means working along the row.    
# Percentile of the flattened array 
print("\n5th Percentile of arr, axis = None : ", 
      np.percentile(arr, 5)) 
print("95th Percentile of arr, axis = None : ", 
      np.percentile(arr, 95))   
# Percentile along the axis = 0 
print("\n5th Percentile of arr, axis = 0 : ", 
      np.percentile(arr, 5, axis =0)) 
print("95th Percentile of arr, axis = 0 : ", 
      np.percentile(arr, 95, axis =0)) 
print("_________________________________________________")

arr: [[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]]

5th Percentile of arr, axis = None :  1.7000000000000002
95th Percentile of arr, axis = None :  46.999999999999986

5th Percentile of arr, axis = 0 :  [14.1  2.4 13.5  1.7  5.5]
95th Percentile of arr, axis = 0 :  [22.2 15.9 51.3 30.5 41.5]
_________________________________________________


In [21]:
#Question:15
#How to find if a given array has any null values?
print("Original array:")
nums = np.random.randint(0,3,(4,10))
print(nums)
print("\nIs NaN: \n", np.isnan(nums)) 
print("\nTest whether the said array has null values or not:")
n=np.all(np.isnan(nums))
print(n)
print("_________________________________________________")


Original array:
[[1 0 1 0 1 0 0 1 2 0]
 [0 2 2 1 0 2 1 2 0 0]
 [1 0 1 1 1 1 0 2 1 1]
 [2 1 0 0 1 0 1 1 1 0]]

Is NaN: 
 [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]

Test whether the said array has null values or not:
False
_________________________________________________


# END